package main

import (
	"flag"
	"html/template"
	"log"
	"os"
	"path/filepath"
	"strings"

	s3 "github.com/panyam/s3gen"
)

var (
	addr  = flag.String("addr", DefaultAddress(), "Address where the http server is running")
	build = flag.Bool("build", false, "Build the site once and quit, instead of serving it")
)

// projectRoot is the absolute path to the docsite directory.
var projectRoot string

func init() {
	var err error
	projectRoot, err = filepath.Abs(".")
	if err != nil {
		log.Fatalf("Failed to get project root: %v", err)
	}
}

// IncludeFile returns a file's contents as raw (unescaped) HTML. The path is
// relative to the docsite directory and cannot escape it.
func IncludeFile(relativePath string) template.HTML {
	absPath, ok := safeJoin(relativePath)
	if !ok {
		return ""
	}
	data, err := os.ReadFile(absPath)
	if err != nil {
		return ""
	}
	return template.HTML(data)
}

// IncludeFileText returns a file's contents as plain (escaped) text. Useful for
// showing source snippets.
func IncludeFileText(relativePath string) string {
	absPath, ok := safeJoin(relativePath)
	if !ok {
		return ""
	}
	data, err := os.ReadFile(absPath)
	if err != nil {
		return ""
	}
	return string(data)
}

// IncludeCard returns a GENERATED catalog card's markdown body, frontmatter stripped, for
// transcluding a rule or relation reference into the guide page that teaches it (WS14-006).
//
// It exists so a card has ONE source. The cards under content/reference/ are generated by
// `make catalog-docs` from the rule and relation definitions themselves, and a guide page that
// copied one would be a second copy that silently rots the next time the rule's Detail changes.
// Transcluding keeps the generator authoritative and the guide page a pointer.
//
// The frontmatter has to go: it is the CARD's page metadata (its own title and description), and
// leaving it in renders the raw "title: ..." lines as a stray heading inside the host page, which is
// exactly what the first attempt did. Body only, so the host page keeps its own heading hierarchy.
//
// Cards open at h3, which is deliberate: a guide page introduces one under its own h2, so the levels
// nest without rewriting either side.
func IncludeCard(relativePath string) string {
	absPath, ok := safeJoin(relativePath)
	if !ok {
		return ""
	}
	data, err := os.ReadFile(absPath)
	if err != nil {
		log.Printf("includeCard: %v", err)
		return ""
	}
	return stripFrontmatter(string(data))
}

// stripFrontmatter removes a leading YAML frontmatter block. A file without one is returned
// unchanged, so this is safe on a hand-written include as well as a generated card.
func stripFrontmatter(s string) string {
	s = strings.TrimLeft(s, "\n")
	if !strings.HasPrefix(s, "---\n") {
		return s
	}
	if end := strings.Index(s[4:], "\n---"); end >= 0 {
		rest := s[4+end+4:]
		return strings.TrimLeft(rest, "\n")
	}
	return s // unterminated frontmatter: leave it alone rather than eat the file
}

// safeJoin resolves a project-relative path and rejects traversal.
func safeJoin(relativePath string) (string, bool) {
	cleanPath := filepath.Clean(relativePath)
	if filepath.IsAbs(cleanPath) || strings.HasPrefix(cleanPath, "..") {
		log.Printf("include: rejected path %q (absolute or escaping)", relativePath)
		return "", false
	}
	fullPath := filepath.Join(projectRoot, cleanPath)
	absPath, err := filepath.Abs(fullPath)
	if err != nil || !strings.HasPrefix(absPath, projectRoot) {
		log.Printf("include: rejected path %q (escapes project root)", relativePath)
		return "", false
	}
	return absPath, true
}

// PathPrefix is the URL prefix every page and asset is served under.
//
// It is a const rather than a field read off Site because Explainable needs it to build a term's
// URL, and Site's own literal references Explainable. Go reads that as an initialization cycle, so
// the prefix has to exist independently of the value that carries it.
const PathPrefix = "/agni"

// Site is the s3gen configuration for the Agni documentation site.
var Site = &s3.Site{
	OutputDir:   "./dist",
	ContentRoot: "./content",

	// URL path prefix. The GitHub Pages site is served at
	// https://panyam.github.io/agni/, so pages live under /agni.
	PathPrefix: PathPrefix,

	TemplateFolders: []string{
		"./templates",
	},

	StaticFolders: []string{
		"/static/",
		"./static",
	},

	DefaultBaseTemplate: s3.BaseTemplate{
		Name: "BasePage.html",
		Params: map[any]any{
			"BodyTemplateName": "Content",
		},
	},

	CommonFuncMap: map[string]any{
		"includeFile":     IncludeFile,
		"includeFileText": IncludeFileText,
		"includeCard":     IncludeCard,
		"agniRun":         AgniRun,
		"explainable":     Explainable,
		"explainableCap":  ExplainableCap,

		// String/content helpers the templates use. Newer s3gen provides
		// these via its default func map; the pinned version does not, so we
		// supply them here to keep the site self-contained.
		"Contains":      strings.Contains,
		"HasPrefix":     strings.HasPrefix,
		"HasSuffix":     strings.HasSuffix,
		"BytesToString": func(b []byte) string { return string(b) },
		"HTML":          func(s string) template.HTML { return template.HTML(s) },
	},
}

func main() {
	flag.Parse()

	// Build once, then serve. There is no file watcher: the live-reload path did not work, and without
	// it `-build` actually terminates — which is what a build STEP needs, and what a watcher blocking
	// forever prevented.
	Site.Rebuild(nil)

	if !*build {
		Site.Serve(*addr)
	}
}

func DefaultAddress() string {
	if a := os.Getenv("AGNI_DOCS_PORT"); a != "" {
		return a
	}
	return ":8080"
}
