package projects

import (
	"bytes"
	"strings"
	"testing"
)

// TestDescriptorRoundTrip is why the writer lives in this package. The parser is strict — an unknown
// field is an error, not an ignored line — so a scaffolder marshalling its own struct would produce
// descriptors its own parser rejects the moment either side gained a field. Writing through the same
// shapes makes that impossible rather than unlikely.
func TestDescriptorRoundTrip(t *testing.T) {
	t.Run("project, nothing declared", func(t *testing.T) {
		var b bytes.Buffer
		if err := WriteProject(&b, "generated by agni start\nedit freely", "gateway", "Gateway ECU", nil); err != nil {
			t.Fatalf("WriteProject: %v", err)
		}
		if !strings.HasPrefix(b.String(), "# generated by agni start\n# edit freely\n") {
			t.Errorf("header should be written as YAML comments, got:\n%s", b.String())
		}
		id, p, names, err := ParseProject(bytes.NewReader(b.Bytes()))
		if err != nil {
			t.Fatalf("ParseProject: %v", err)
		}
		if id != "gateway" || p.GetTitle() != "Gateway ECU" {
			t.Errorf("round trip lost identity: id=%q title=%q", id, p.GetTitle())
		}
		// Declaring nothing must resolve to the conventional names, which is the whole reason a
		// scaffolder can write the layout without naming any of it.
		want := ProjectConfigNames{Conventions: defaultConventions, Profiles: defaultProfiles, Params: defaultParams, Checklist: defaultChecklist}
		if names != want {
			t.Errorf("undeclared config should fall back to the defaults, got %+v want %+v", names, want)
		}
	})

	t.Run("project, config declared", func(t *testing.T) {
		var b bytes.Buffer
		in := ProjectConfigNames{Conventions: "house.yaml", Profiles: "ifaces", Params: "specs", Checklist: "checklists/board.yaml"}
		if err := WriteProject(&b, "", "p", "P", &in); err != nil {
			t.Fatalf("WriteProject: %v", err)
		}
		_, _, names, err := ParseProject(bytes.NewReader(b.Bytes()))
		if err != nil {
			t.Fatalf("ParseProject: %v", err)
		}
		if names != in {
			t.Errorf("declared config did not survive the round trip, got %+v want %+v", names, in)
		}
	})

	t.Run("design with companions", func(t *testing.T) {
		var b bytes.Buffer
		if err := WriteDesign(&b, "", "gateway", "Gateway", "./gateway.edn", []string{"gateway.kicad_pcb", "./gateway.eds"}); err != nil {
			t.Fatalf("WriteDesign: %v", err)
		}
		id, d, err := ParseDesign(bytes.NewReader(b.Bytes()))
		if err != nil {
			t.Fatalf("ParseDesign: %v", err)
		}
		if id != "gateway" {
			t.Errorf("id = %q", id)
		}
		// Written paths are cleaned on the way in, so a caller passing "./x" cannot produce a
		// descriptor whose entry differs from what the parser will resolve.
		if got := d.GetEntryUri(); !strings.HasSuffix(got, "gateway.edn") || strings.Contains(got, "./") {
			t.Errorf("entry = %q, want a cleaned gateway.edn", got)
		}
		if n := len(d.GetCompanionUris()); n != 2 {
			t.Errorf("companions = %d, want 2", n)
		}
	})
}

// TestWriteDescriptorRejectsBadIds: an id becomes a path segment in a resource name, so a writer that
// accepted a slash or an uppercase letter would produce a descriptor the parser refuses, from a
// command that reported success.
func TestWriteDescriptorRejectsBadIds(t *testing.T) {
	for _, id := range []string{"", "Gateway", "a/b", "-lead"} {
		if err := WriteProject(&bytes.Buffer{}, "", id, "T", nil); err == nil {
			t.Errorf("WriteProject accepted id %q", id)
		}
		if err := WriteDesign(&bytes.Buffer{}, "", id, "T", "x.edn", nil); err == nil {
			t.Errorf("WriteDesign accepted id %q", id)
		}
	}
	if err := WriteDesign(&bytes.Buffer{}, "", "ok", "T", "", nil); err == nil {
		t.Error("WriteDesign accepted an empty entry; a design with no entry names no analysis source")
	}
}
