# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agni/v1/webapi/config.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'agni/v1/webapi/config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from agni.v1.config import naming_pb2 as agni_dot_v1_dot_config_dot_naming__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61gni/v1/webapi/config.proto\x12\x0e\x61gni.v1.webapi\x1a\x1b\x61gni/v1/config/naming.proto\"\xc6\x04\n\x0e\x41nalysisConfig\x12\x42\n\x0b\x63onventions\x18\x01 \x01(\x0b\x32 .agni.v1.config.NamingConventionR\x0b\x63onventions\x12\'\n\x0f\x63onventions_uri\x18\x02 \x01(\tR\x0e\x63onventionsUri\x12!\n\x0cprofile_uris\x18\x03 \x03(\tR\x0bprofileUris\x12\x1d\n\nparam_uris\x18\x04 \x03(\tR\tparamUris\x12#\n\rchecklist_uri\x18\x05 \x01(\tR\x0c\x63hecklistUri\x12\x1d\n\nintent_uri\x18\x06 \x01(\tR\tintentUri\x12\x18\n\x07\x65xtends\x18\x07 \x01(\tR\x07\x65xtends\x12(\n\x10symbol_path_uris\x18\x08 \x03(\tR\x0esymbolPathUris\x12!\n\x0clibrary_uris\x18\t \x03(\tR\x0blibraryUris\x12\x46\n\x0flibrary_modules\x18\n \x03(\x0b\x32\x1d.agni.v1.webapi.LibraryModuleR\x0elibraryModules\x12R\n\x0clibrary_docs\x18\x0b \x03(\x0b\x32/.agni.v1.webapi.AnalysisConfig.LibraryDocsEntryR\x0blibraryDocs\x1a>\n\x10LibraryDocsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"k\n\rLibraryModule\x12\x12\n\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n\x08language\x18\x02 \x01(\tR\x08language\x12\x12\n\x04text\x18\x03 \x01(\tR\x04text\x12\x16\n\x06source\x18\x04 \x01(\tR\x06sourceB.Z,github.com/panyam/agni/gen/go/agni/v1/webapib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agni.v1.webapi.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/panyam/agni/gen/go/agni/v1/webapi'
  _globals['_ANALYSISCONFIG_LIBRARYDOCSENTRY']._loaded_options = None
  _globals['_ANALYSISCONFIG_LIBRARYDOCSENTRY']._serialized_options = b'8\001'
  _globals['_ANALYSISCONFIG']._serialized_start=77
  _globals['_ANALYSISCONFIG']._serialized_end=659
  _globals['_ANALYSISCONFIG_LIBRARYDOCSENTRY']._serialized_start=597
  _globals['_ANALYSISCONFIG_LIBRARYDOCSENTRY']._serialized_end=659
  _globals['_LIBRARYMODULE']._serialized_start=661
  _globals['_LIBRARYMODULE']._serialized_end=768
# @@protoc_insertion_point(module_scope)
