# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agni/v1/webapi/validate.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'agni/v1/webapi/validate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61gni/v1/webapi/validate.proto\x12\x0e\x61gni.v1.webapi\"\x90\x01\n\x0eValidateReport\x12\x34\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x1e.agni.v1.webapi.FileValidationR\x05\x66iles\x12\x16\n\x06passed\x18\x02 \x01(\x05R\x06passed\x12\x16\n\x06\x66\x61iled\x18\x03 \x01(\x05R\x06\x66\x61iled\x12\x18\n\x07skipped\x18\x04 \x01(\x05R\x07skipped\"\xdd\x01\n\x0e\x46ileValidation\x12\x12\n\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n\x06\x66ormat\x18\x02 \x01(\tR\x06\x66ormat\x12\x0e\n\x02ok\x18\x03 \x01(\x08R\x02ok\x12\x1a\n\x08problems\x18\x04 \x03(\tR\x08problems\x12\x37\n\x07netlist\x18\x05 \x01(\x0b\x32\x1d.agni.v1.webapi.NetlistCountsR\x07netlist\x12:\n\x08geometry\x18\x06 \x01(\x0b\x32\x1e.agni.v1.webapi.GeometryCountsR\x08geometry\"C\n\rNetlistCounts\x12\x1e\n\ncomponents\x18\x01 \x01(\x05R\ncomponents\x12\x12\n\x04nets\x18\x02 \x01(\x05R\x04nets\"\x94\x01\n\x0eGeometryCounts\x12\x16\n\x06sheets\x18\x01 \x01(\x05R\x06sheets\x12\x18\n\x07symbols\x18\x02 \x01(\x05R\x07symbols\x12\x1e\n\nplacements\x18\x03 \x01(\x05R\nplacements\x12\x14\n\x05wires\x18\x04 \x01(\x05R\x05wires\x12\x1a\n\x08resolved\x18\x05 \x01(\x05R\x08resolvedB.Z,github.com/panyam/agni/gen/go/agni/v1/webapib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agni.v1.webapi.validate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/panyam/agni/gen/go/agni/v1/webapi'
  _globals['_VALIDATEREPORT']._serialized_start=50
  _globals['_VALIDATEREPORT']._serialized_end=194
  _globals['_FILEVALIDATION']._serialized_start=197
  _globals['_FILEVALIDATION']._serialized_end=418
  _globals['_NETLISTCOUNTS']._serialized_start=420
  _globals['_NETLISTCOUNTS']._serialized_end=487
  _globals['_GEOMETRYCOUNTS']._serialized_start=490
  _globals['_GEOMETRYCOUNTS']._serialized_end=638
# @@protoc_insertion_point(module_scope)
