package service

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"

	"github.com/panyam/agni/core/query"
)

// Column-kind equivalence, captured before the declaration replaced the inference (agni issue 548).
//
// Deciding a column's entity kind used to be a string match on the catalog's human-facing ARG
// LABELS: "ref_des" meant a component, "pin" meant a design pin but only when a "ref_des" sat beside
// it, "name" meant a polymorphic column but only when a "kind" sat beside it. Replacing that with a
// declaration is exactly the change where a quiet behaviour shift hides, because nothing downstream
// would fail loudly on a column that silently stopped being clickable.
//
// So the answers are pinned first. The corpus is GENERATED from the catalog rather than written by
// hand, so every relation and every argument position is covered, and a relation added later shows
// up as a new golden line rather than as untested silence.
//
// Regenerate deliberately with -update, and read the diff: a changed line is a column that changed
// kind, which is either the point of your change or a bug.
func TestColumnKindsMatchGolden(t *testing.T) {
	got := columnKindsSnapshot(t)
	path := filepath.Join("testdata", "columnkinds.golden")
	if os.Getenv("UPDATE_GOLDEN") != "" {
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Log("golden updated; read the diff before committing it")
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden: %v (regenerate with UPDATE_GOLDEN=1)", err)
	}
	if got != string(want) {
		t.Errorf("column kinds changed. Every line is a query column that types differently than it "+
			"did, so read the diff rather than regenerating:\n%s", firstDiff(string(want), got))
	}
}

// columnKindsSnapshot renders columnKinds' answer for one generated query per catalogued relation.
func columnKindsSnapshot(t *testing.T) string {
	t.Helper()
	cat := query.Catalog()
	sort.Slice(cat, func(i, j int) bool { return cat[i].Name < cat[j].Name })

	var b strings.Builder
	for _, ri := range cat {
		q, err := query.Parse(generatedQuery(ri.Name, len(ri.Args)))
		if err != nil {
			// A predicate with a shape the generator cannot spell is recorded as such rather than
			// skipped, so it cannot quietly leave the corpus.
			fmt.Fprintf(&b, "%s\tUNPARSEABLE\t%v\n", ri.Name, err)
			continue
		}
		kinds, kindVars, refs := columnKinds(q)
		for i := range kinds {
			fmt.Fprintf(&b, "%s\targ%d=%s\tkind=%q\tkindVar=%q\tref=%s\n",
				ri.Name, i, ri.Args[i], kinds[i], kindVars[i], termString(refs[i]))
		}
	}
	return b.String()
}

// generatedQuery spells one relation with a distinct variable per argument, projecting all of them,
// so every position is a column columnKinds has to type.
func generatedQuery(rel string, arity int) string {
	vars := make([]string, arity)
	for i := range vars {
		vars[i] = fmt.Sprintf("?a%d", i)
	}
	joined := strings.Join(vars, ", ")
	return fmt.Sprintf("%s(%s) => %s", rel, joined, joined)
}

// termString renders a ref term for the golden, where "" means the column carries no owning entity.
func termString(t query.Term) string {
	switch {
	case t.Var != "":
		return "?" + string(t.Var)
	case t.Const != nil:
		return strconv.Quote(t.Const.S)
	default:
		return "-"
	}
}

// firstDiff reports the first differing line with a little context, so a failure names the column
// that moved instead of printing two hundred identical ones.
func firstDiff(want, got string) string {
	w, g := strings.Split(want, "\n"), strings.Split(got, "\n")
	for i := 0; i < len(w) || i < len(g); i++ {
		var wl, gl string
		if i < len(w) {
			wl = w[i]
		}
		if i < len(g) {
			gl = g[i]
		}
		if wl != gl {
			return fmt.Sprintf("line %d\n  want: %s\n  got:  %s", i+1, wl, gl)
		}
	}
	return "(no line differs; trailing whitespace?)"
}

// TestPinColumnNeedsItsComponent states, as prose rather than as a snapshot line, the distinction the
// old inference needed a hand-written pairing guard for. The golden pins it too, but a golden can be
// regenerated by someone who did not know it mattered.
//
// A design pin is locatable because the relation says which placement it belongs to. A datasheet pin
// belongs to a part TYPE, and a part type is not on the canvas: fifty instances of one MPN share it,
// so there is no single thing to highlight.
func TestPinColumnNeedsItsComponent(t *testing.T) {
	design, err := query.Parse("pin.net(?r, ?p, ?n) => ?p")
	if err != nil {
		t.Fatal(err)
	}
	kinds, _, refs := columnKinds(design)
	if kinds[0] != "pin" {
		t.Errorf("pin.net's pin column kind = %q, want pin", kinds[0])
	}
	if refs[0].Var != "r" {
		t.Errorf("pin.net's pin column owner = %+v, want the ref_des variable", refs[0])
	}

	spec, err := query.Parse("param.pin(?m, ?p, ?name, ?fn) => ?p")
	if err != nil {
		t.Fatal(err)
	}
	kinds, _, refs = columnKinds(spec)
	if kinds[0] != "" || refs[0].Var != "" {
		t.Errorf("param.pin's pin column typed as %q/%+v, want a scalar: it is a pin of a part type", kinds[0], refs[0])
	}
}

// TestPolymorphicColumnTakesItsKindFromTheDeclaredArgument covers the other deleted guard. entity is
// the one relation whose answer says what each row is about, so its name column is typed per row;
// bus and param.range also carry a `kind` argument and neither types anything by it.
func TestPolymorphicColumnTakesItsKindFromTheDeclaredArgument(t *testing.T) {
	perRow, err := query.Parse("entity(?n, ?k) => ?n")
	if err != nil {
		t.Fatal(err)
	}
	kinds, kindVars, _ := columnKinds(perRow)
	if kinds[0] != "" || kindVars[0] != "k" {
		t.Errorf("entity(?n, ?k) name column = kind %q kindVar %q, want it typed per row by ?k", kinds[0], kindVars[0])
	}

	static, err := query.Parse(`entity(?n, "net") => ?n`)
	if err != nil {
		t.Fatal(err)
	}
	kinds, kindVars, _ = columnKinds(static)
	if kinds[0] != "net" || kindVars[0] != "" {
		t.Errorf(`entity(?n, "net") name column = kind %q kindVar %q, want a static net column`, kinds[0], kindVars[0])
	}

	// bus carries a `kind` argument that is a bus KIND, not an entity kind, and declares nothing.
	busQ, err := query.Parse("bus(?l, ?k) => ?l, ?k")
	if err != nil {
		t.Fatal(err)
	}
	kinds, kindVars, _ = columnKinds(busQ)
	for i, col := range []string{"label", "kind"} {
		if kinds[i] != "" || kindVars[i] != "" {
			t.Errorf("bus %s column = kind %q kindVar %q, want a scalar", col, kinds[i], kindVars[i])
		}
	}
}
