# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agni/v1/param/service.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'agni/v1/param/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from agni.v1.param import param_pb2 as agni_dot_v1_dot_param_dot_param__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61gni/v1/param/service.proto\x12\ragni.v1.param\x1a\x19\x61gni/v1/param/param.proto\".\n\x18\x42\x61tchGetPartSpecsRequest\x12\x12\n\x04mpns\x18\x01 \x03(\tR\x04mpns\"j\n\x19\x42\x61tchGetPartSpecsResponse\x12-\n\x05specs\x18\x01 \x03(\x0b\x32\x17.agni.v1.param.PartSpecR\x05specs\x12\x1e\n\ngeneration\x18\x02 \x01(\x04R\ngeneration\"\x16\n\x14GetGenerationRequest\"7\n\x15GetGenerationResponse\x12\x1e\n\ngeneration\x18\x01 \x01(\x04R\ngeneration2\xd5\x01\n\x0fPartSpecService\x12\x66\n\x11\x42\x61tchGetPartSpecs\x12\'.agni.v1.param.BatchGetPartSpecsRequest\x1a(.agni.v1.param.BatchGetPartSpecsResponse\x12Z\n\rGetGeneration\x12#.agni.v1.param.GetGenerationRequest\x1a$.agni.v1.param.GetGenerationResponseB-Z+github.com/panyam/agni/gen/go/agni/v1/paramb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agni.v1.param.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/panyam/agni/gen/go/agni/v1/param'
  _globals['_BATCHGETPARTSPECSREQUEST']._serialized_start=73
  _globals['_BATCHGETPARTSPECSREQUEST']._serialized_end=119
  _globals['_BATCHGETPARTSPECSRESPONSE']._serialized_start=121
  _globals['_BATCHGETPARTSPECSRESPONSE']._serialized_end=227
  _globals['_GETGENERATIONREQUEST']._serialized_start=229
  _globals['_GETGENERATIONREQUEST']._serialized_end=251
  _globals['_GETGENERATIONRESPONSE']._serialized_start=253
  _globals['_GETGENERATIONRESPONSE']._serialized_end=308
  _globals['_PARTSPECSERVICE']._serialized_start=311
  _globals['_PARTSPECSERVICE']._serialized_end=524
# @@protoc_insertion_point(module_scope)
