# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agni/v1/candidate/candidate.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'agni/v1/candidate/candidate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from agni.v1.param import param_pb2 as agni_dot_v1_dot_param_dot_param__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!agni/v1/candidate/candidate.proto\x12\x11\x61gni.v1.candidate\x1a\x19\x61gni/v1/param/param.proto\"3\n\x07Request\x12\x10\n\x03mpn\x18\x01 \x01(\tR\x03mpn\x12\x16\n\x06symbol\x18\x02 \x01(\tR\x06symbol\"u\n\x08\x43itation\x12\x12\n\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n\tregion_id\x18\x02 \x01(\tR\x08regionId\x12\x10\n\x03row\x18\x03 \x01(\x05R\x03row\x12\x10\n\x03\x63ol\x18\x04 \x01(\x05R\x03\x63ol\x12\x14\n\x05quote\x18\x05 \x01(\tR\x05quote\"\xb0\x02\n\tCandidate\x12\x34\n\x07request\x18\x01 \x01(\x0b\x32\x1a.agni.v1.candidate.RequestR\x07request\x12\x37\n\x08\x63itation\x18\x02 \x01(\x0b\x32\x1b.agni.v1.candidate.CitationR\x08\x63itation\x12/\n\x05value\x18\x03 \x01(\x0b\x32\x19.agni.v1.param.RangeValueR\x05value\x12\x12\n\x04unit\x18\x04 \x01(\tR\x04unit\x12\x37\n\nlimit_kind\x18\x05 \x01(\x0e\x32\x18.agni.v1.param.LimitKindR\tlimitKind\x12\x16\n\x06source\x18\x06 \x01(\tR\x06source\x12\x1e\n\nconfidence\x18\x07 \x01(\x01R\nconfidenceB1Z/github.com/panyam/agni/gen/go/agni/v1/candidateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agni.v1.candidate.candidate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/panyam/agni/gen/go/agni/v1/candidate'
  _globals['_REQUEST']._serialized_start=83
  _globals['_REQUEST']._serialized_end=134
  _globals['_CITATION']._serialized_start=136
  _globals['_CITATION']._serialized_end=253
  _globals['_CANDIDATE']._serialized_start=256
  _globals['_CANDIDATE']._serialized_end=560
# @@protoc_insertion_point(module_scope)
