// query.ts is the framework-neutral state for the datalog query panel (WS9-036). The presenter
// pushes a QueryResult and the panel renders it. The shape lives here rather than in the .tsx, as in
// rules.ts and findings.ts, so the presenter and tests build state without touching Solid.
import { type RunQueryResponse } from "./gen/agni/v1/webapi/query_pb.js";
import { LocateReason } from "./gen/agni/v1/checks/checks_pb.js";
import type { FindingsState, SheetBadge } from "./findings.js";
import type { Selection } from "./selection.js";

export { LocateReason };

// QueryRowItem is one answer row. cells align positionally with QueryResult.columns, and cites is
// the row's provenance, shown on demand so the table stays narrow. cellSheets aligns with cells and
// holds the sheet badges a navigable cell (component/net) can jump to (WS9-038), [] for a scalar or
// unlocated cell.
export interface QueryRowItem {
  cells: string[];
  cites: string[];
  cellSheets: SheetBadge[][];
  cellReasons: LocateReason[];
  // cellKinds aligns with cells and overrides columnKinds for this row (agni issue 338). It is ""
  // everywhere except a POLYMORPHIC column, where the answer set holds more than one sort of thing
  // and the column cannot say which. Read it through cellKind, never directly.
  cellKinds: string[];
  // cellRefs aligns with cells and carries the other half of a cell's identity, which today means a
  // pin cell's component. "" everywhere else.
  cellRefs: string[];
}

// QueryResult is the panel's whole state. `ran` distinguishes "not run yet" (blank panel) from
// "ran and matched nothing" (no results). `error` is the inline message for a bad query or an
// unloadable design; when set, columns/rows are empty. `loading` gates the run button. columnKinds
// aligns with columns ("component" | "net" | "" scalar) and decides which cells are clickable to
// locate the entity in the canvas (WS9-038).
export interface QueryResult {
  columns: string[];
  columnKinds: string[];
  rows: QueryRowItem[];
  error: string;
  loading: boolean;
  ran: boolean;
}

// RelationItem is one entry in the relation picker (WS9-037). It holds the name, the arg labels a
// template inserts as ?arg, a one-line summary (hover), a kind for grouping, and (WS14-005) the
// reference markdown the panel renders on demand ("" when the relation has no doc yet).
export interface RelationItem {
  name: string;
  args: string[];
  summary: string;
  kind: string;
  detail: string;
}

// ExampleItem is one starter query (WS14-002), holding a plain-language label, the datalog query a
// click fills and runs, and the concept it teaches. The server orders them as a concept ladder.
export interface ExampleItem {
  label: string;
  query: string;
  teaches: string;
}

// QueryView is the command-down surface. The presenter (or the composition root, for the static
// relation and example catalog) calls setState with each result, and setRelations/setExamples once
// at boot. setLocateNote pushes the WS9-039 explanation shown when a cell click highlighted nothing
// ("" to clear it). The presenter drives the note because only it knows whether the highlight
// resolved.
export interface QueryView {
  setState: (s: QueryResult) => void;
  setRelations: (rels: RelationItem[]) => void;
  setExamples: (examples: ExampleItem[]) => void;
  setLocateNote: (message: string) => void;
  // setQuery hands the panel a query written FOR the reader, today one generated by clicking an
  // entity on the drawing, with the values its variables are bound to (agni issue 793). It fills the
  // box and the binding chips and runs, leaving an editable query behind.
  setQuery: (text: string, bindings?: Record<string, string>) => void;
  // setEntityQueries hands over the click-to-ask presets from the server, keyed by entity kind.
  setEntityQueries: (presets: EntityQueryItem[]) => void;
  // setSearch hands over the find-by-name template. Until it arrives the panel offers no search
  // mode, rather than one that would run a guessed query.
  setSearch: (search: SearchItem | null) => void;
  // setSelection names the entity the reader last picked on the drawing, so the panel can say what
  // is selected and offer the question to ask about it next. Clicking a result cell selects too,
  // but the panel handles that itself. This is the entry point for the OTHER picker, the canvas.
  setSelection: (sel: Selection | null) => void;
  // setFindings hands over the CURRENT check results, whole (agni issue 259). The panel projects
  // them onto whatever is selected and re-runs nothing, since it holds no client. It takes the full
  // state rather than a count because `pending` and `running` separate "nothing is wrong with this
  // net" from "nobody has checked".
  setFindings: (state: FindingsState) => void;
  // setCurrentSheet names the sheet on screen. The panel marks the badge that points at it, so a
  // reader who navigated away can still see which answer they navigated FROM.
  setCurrentSheet: (sheetId: string) => void;
  // entityQuery returns the preset for one entity kind, or undefined before the catalog has arrived.
  // A click then still highlights and asks nothing, rather than running a guess.
  entityQuery: (kind: string) => EntityQueryItem | undefined;
}

// EntityQueryItem is one served preset. query is the datalog a click on this kind of entity runs,
// and binds names the variables the client binds from the selection (see entityBindings in
// selection.ts).
export interface EntityQueryItem {
  kind: string;
  query: string;
  teaches: string;
  binds: string[];
}

// RELATION_KINDS is the group order + display label for the picker; a kind absent here (or with no
// members) renders no group. Mirrors query.KindOrder on the server, but the client owns display.
export const RELATION_KINDS: readonly { key: string; label: string }[] = [
  { key: "netlist", label: "Netlist" },
  { key: "board", label: "Board" },
  { key: "datasheet", label: "Datasheet" },
  { key: "derived", label: "Library" },
  { key: "predicate", label: "Predicates" },
  { key: "overlay", label: "Overlay" },
];

// relationTemplate renders a relation as an insertable snippet: name(?arg1, ?arg2). A zero-arg
// relation (none today) inserts name().
export function relationTemplate(r: RelationItem): string {
  return `${r.name}(${r.args.map((a) => "?" + a).join(", ")})`;
}

// cellKind returns the kind of one result cell, the row's own if it has one, else the column's.
// Kind is usually a column property because a variable binds at the same relation position in every
// row, EXCEPT under a relation whose answer says what each row is about (entity(?name, ?kind), agni
// issue 338). Every reader of a cell's kind goes through here so the two sources never drift apart.
// An ordinary query carries no cellKinds and falls through to the column.
export function cellKind(result: QueryResult, row: QueryRowItem, i: number): string {
  return row.cellKinds[i] || result.columnKinds[i] || "";
}

// SearchItem is the served find-by-name query (agni issue 338) and the concept it leaves behind. A
// search binds the variable `bind` names to `pattern` with {term} replaced by the escaped term
// (agni issue 793), so the query text never changes. It is served rather than written here because
// it names `entity` and `str.match`, both defined in Go, and the pattern holds the (?i).
export interface SearchItem {
  query: string;
  teaches: string;
  bind: string;
  pattern: string;
}

// searchPattern turns what a reader TYPED into a regex that matches it literally, mirroring Go's
// regexp.QuoteMeta. A design is full of names the regex engine would otherwise read as syntax
// (VDD+, USB_D-, DATA[7:0], VREF(A)), and a reader typing one of those means the characters. A
// double quote is kept, since the pattern is bound as a value rather than spliced into a string
// literal (agni issue 793).
export function searchPattern(term: string): string {
  return term.replace(/[\\.+*?()|[\]{}^$]/g, "\\$&");
}

// searchBindings is what a search binds: the served pattern with {term} replaced by the escaped
// term. split/join rather than replace, because a replacement string reads `$&` and `$1` as syntax.
// The caller handles an empty term, and the panel refuses to run one rather than enumerate a whole
// design into a table that renders every row.
export function searchBindings(search: SearchItem, term: string): Record<string, string> {
  return { [search.bind]: search.pattern.split("{term}").join(searchPattern(term)) };
}

// bindingsInUse keeps the bindings whose variable the query text still names. A reader who edits a
// bound variable out of the query has stopped asking about it, and the server refuses a binding the
// goal does not use.
export function bindingsInUse(text: string, bindings: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [name, value] of Object.entries(bindings)) {
    if (new RegExp(`\\?${name.replace(/[^\w]/g, "")}\\b`).test(text)) out[name] = value;
  }
  return out;
}

// formatBinding spells one binding as the query would write the constant, for a chip or a tooltip.
export function formatBinding(name: string, value: string): string {
  return `?${name} = ${JSON.stringify(value)}`;
}

// groupRelations buckets the catalog by kind in RELATION_KINDS order, each bucket sorted by name.
// Kinds not in RELATION_KINDS are appended in first-seen order so an overlay's novel kind still
// shows. Empty buckets are dropped.
export function groupRelations(rels: RelationItem[]): { key: string; label: string; items: RelationItem[] }[] {
  const byKind = new Map<string, RelationItem[]>();
  for (const r of rels) {
    const list = byKind.get(r.kind) ?? [];
    list.push(r);
    byKind.set(r.kind, list);
  }
  const order = [...RELATION_KINDS];
  for (const k of byKind.keys()) {
    if (!order.some((o) => o.key === k)) order.push({ key: k, label: k });
  }
  const out: { key: string; label: string; items: RelationItem[] }[] = [];
  for (const { key, label } of order) {
    const items = byKind.get(key);
    if (items && items.length > 0) {
      out.push({ key, label, items: [...items].sort((a, b) => a.name.localeCompare(b.name)) });
    }
  }
  return out;
}

// emptyResult is the initial state (nothing run yet) and the reset the panel shows while a query
// is in flight.
export function emptyResult(loading = false): QueryResult {
  return { columns: [], columnKinds: [], rows: [], error: "", loading, ran: false };
}

// resultFromResponse projects a RunQueryResponse into panel state. The injected resolver turns
// each navigable cell's sheet ids into display badges (the presenter's sheetBadges, which
// suppresses badges on a single-sheet design and maps id->name). The default yields no badges, so
// tests need not pass one.
export function resultFromResponse(
  resp: RunQueryResponse,
  resolveSheets: (ids: string[]) => SheetBadge[] = () => [],
): QueryResult {
  return {
    columns: resp.columns,
    columnKinds: resp.columnKinds ?? [],
    // An entity cell's sheets and reason, and a row's citations, are kept once on the response and
    // the row points into them (agni issue 916).
    rows: resp.rows.map((r) => {
      const entity = (i: number) => {
        const n = r.cellEntity?.[i] ?? 0;
        return n > 0 ? resp.entities?.[n - 1] : undefined;
      };
      return {
        cells: r.cells,
        cites: (r.citeIndex ?? []).map((i) => resp.sources?.[i] ?? ""),
        cellSheets: r.cells.map((_, i) => resolveSheets(entity(i)?.sheetIds ?? [])),
        cellReasons: r.cells.map((_, i) => entity(i)?.reason ?? LocateReason.UNSPECIFIED),
        cellKinds: r.cells.map((_, i) => r.cellKinds?.[i] ?? ""),
        cellRefs: r.cells.map((_, i) => r.cellRefs?.[i] ?? ""),
      };
    }),
    error: "",
    loading: false,
    ran: true,
  };
}

// errorResult wraps a failure message (a parse error, or an unloadable design) as panel state.
export function errorResult(message: string): QueryResult {
  return { columns: [], columnKinds: [], rows: [], error: message, loading: false, ran: true };
}

// reasonMessage renders a locate reason (WS9-039) as the explanation shown when clicking a cell
// highlighted nothing. UNSPECIFIED is the fallback for a normal entity that still did not resolve on
// the current view (an unplaced part, or one that lives on a layout/sheet not shown). The panel owns
// this copy, mirroring how it owns the relation-picker labels.
export function reasonMessage(reason: LocateReason, kind: string, subject: string): string {
  switch (reason) {
    case LocateReason.VIRTUAL_SYMBOL:
      return `${subject} is a power-port/flag symbol (a virtual “#” part), not a placed component — there's nothing to highlight.`;
    case LocateReason.POWER_RAIL_NO_WIRE:
      return `${subject} is a power rail distributed through power-symbol taps, so it has no drawn wire to trace on this schematic view.`;
    case LocateReason.NOT_IN_DESIGN:
      return `${subject} is not in the loaded design.`;
    case LocateReason.BUS_NOT_DRAWN:
      return `${subject} is a bus with no drawn wire on this schematic (a bus alias or a port whose members aren't modeled), so there's nothing to highlight.`;
    default:
      return `Couldn't locate ${kind || "entity"} ${subject} on this view.`;
  }
}
